### ISSUE TITLE
As an unregistered user, I want to be able to register as a user with my chosen credentials (i.e., username and password that are both not empty words) to leverage/use services and information that are exclusively available to registered users. 

### ISSUE THREAD

**Issue by Darnol** [sopra-fs23-group-29/sopra-fs23-group-29-client#1]
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#2
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#3
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#5
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#6
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#84
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#85
